version: '3.8'

services:
    web:
        image: app-name:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        platform: "linux/amd64"
        image: mysql:5.7
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        expose:
            -   3306
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    dbdata:
